config/routes.rb
PolicyManager::Engine.routes.draw do
  get 'documentation', to: 'application#doc', as: :documentation

  resources :user_portability_requests, only: %i[index create destroy]

  resources :portability_requests, only: %i[index destroy] do
    member do
      get :confirm
    end
  end

  resources :categories, only: %i[show index] do
    resources :terms, except: [:index]
  end

  resources :user_terms, only: [:show] do
    collection do
      get :pending
      put :accept_multiples
      get :blocking_terms
    end

    member do
      put :accept
      put :reject
    end
  end

  root 'categories#index'
end

app/models/policy_manager/application_record.rb
module PolicyManager
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/policy_manager/concerns/active_storage_behavior.rb
module PolicyManager::Concerns::ActiveStorageBehavior
  extend ActiveSupport::Concern

  included do
    has_one_attached :attachment
  end

  def file_remote_url=(url_value)
    unless url_value.blank?
      attachment.attach(
        io: File.open(url_value),
        filename: File.basename(url_value),
        content_type: 'application/zip'
      )
    end

    # self.attachment = File.open(url_value) unless url_value.blank?

    save
    complete!
  end

  def download_link
    return '' unless attachment.attached?

    url = Rails.application.routes.url_helpers.rails_blob_path(attachment, only_path: true)
    # self.attachment.expiring_url(PolicyManager::Config.exporter.expiration_link)
    PolicyManager::Config.exporter.customize_link(url)
  end
end

app/models/policy_manager/portability_request.rb
require 'aasm'

module PolicyManager
  class PortabilityRequest < ApplicationRecord
    belongs_to :user, class_name: Config.user_resource.to_s, foreign_key: :user_id

    include PolicyManager::Concerns::ActiveStorageBehavior

    include AASM

    aasm column: :state do
      state :pending, initial: true, after_enter: :notify_progress_to_admin
      state :progress, after_enter: :handle_progress
      state :completed, after_enter: :notify_completeness

      event :confirm do
        transitions from: :pending, to: :progress
      end

      event :complete do
        transitions from: :progress, to: :completed
      end
    end

    def user_email
      user.email
    end

    def handle_progress
      notify_progress
      perform_job
    end

    def perform_job
      ExporterJob.set(queue: :default).perform_later(user.id)
    end

    def notify_progress
      PortabilityMailer.progress_notification(id).deliver_now
    end

    def notify_progress_to_admin
      PortabilityMailer.admin_notification(user.id).deliver_now
    end

    def notify_completeness
      PortabilityMailer.completed_notification(id).deliver_now
    end
  end
end

app/models/policy_manager/term.rb
require 'redcarpet'
require 'aasm'

module PolicyManager
  class Term < ApplicationRecord
    include AASM

    validates_presence_of :rule
    validates_presence_of :description
    validates_presence_of :state

    aasm column: :state do
      state :draft, initial: true # db column's default
      state :published

      event :publish do
        transitions from: :draft, to: :published
      end

      event :unpublish do
        transitions from: :published, to: :draft
      end
    end

    def self.renderer
      @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    end

    def to_html
      self.class.renderer.render(description)
    end

    def rule
      PolicyManager::Config.rules.find { |o| o.name == self[:rule] }
    end
  end
end

app/models/policy_manager/user_term.rb
require 'aasm'

module PolicyManager
  class UserTerm < ApplicationRecord
    include AASM

    belongs_to :user, class_name: Config.user_resource.to_s, foreign_key: :user_id
    belongs_to :term

    validates_uniqueness_of :term_id, scope: :user_id

    aasm column: :state do
      state :passive, initial: true
      state :rejected
      state :accepted

      event :accept do
        transitions from: %i[passive rejected], to: :accepted
      end

      event :reject do
        transitions from: %i[passive accepted], to: :rejected
      end
    end
  end
end

app/controllers/policy_manager/application_controller.rb
module PolicyManager
  class ApplicationController < ActionController::Base
    include Doorman::Controller if defined? Doorman

    before_action :user_authenticated?
    before_action :set_language

    def allow_admins
      redirect_to pending_user_terms_path unless Config.is_admin?(current_user)
    end

    def doc
      require 'redcarpet'
      @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true,
                                                                   fenced_code_blocks: true)
      lines = File.open(PolicyManager::Engine.root.join('README.md')).readlines
      @html = @markdown.render(lines.join(''))
      render 'policy_manager/doc'
      # render inline: html, layout: "policy_manager/application"
    end

    def user_authenticated?
      return if current_user

      render file: 'policy_manager/401.erb',
             layout: 'policy_manager/blank',
             status: :unauthorized
    end

    def set_language
      I18n.locale = Config.user_language(current_user)
    end

    def current_user
      @_current_user ||= super || (Config.has_different_admin_user_resource? && admin_user)
    end

    def admin_user
      send("current_#{Config.admin_user_resource.name.underscore}")
    end

    protect_from_forgery with: :exception
  end
end

app/controllers/policy_manager/categories_controller.rb
require_dependency 'policy_manager/application_controller'

module PolicyManager
  class CategoriesController < ApplicationController
    before_action :allow_admins

    # GET /categories
    def index
      @categories = PolicyManager::Config.rules
    end

    # GET /categories/1
    def show
      @category = PolicyManager::Config.rules.find { |o| o.name == params[:id] }
      @terms = @category.terms.paginate(page: params[:page],
                                        per_page: 20)
    end
  end
end

app/controllers/policy_manager/concerns/user_terms.rb
module PolicyManager::Concerns::UserTerms
  extend ActiveSupport::Concern

  def accept_term(term)
    if current_user
      user_term = current_user.handle_policy_for(term)
      return if user_term.accepted?

      term.rule.on_accept.call(self) if user_term.accept! && term.rule.on_accept.is_a?(Proc)
    end

    cookies["policy_rule_#{term.rule.name}"] = {
      value: 'accepted',
      expires: 1.year.from_now
    }

    user_term
  end

  def reject_term(term)
    if current_user
      user_term = current_user.handle_policy_for(term)
      return if user_term.rejected?

      term.rule.on_reject.call(self) if user_term.reject! && term.rule.on_reject.is_a?(Proc)
    end

    cookies.delete("policy_rule_#{term.rule.name}")

    user_term
  end

  # Use callbacks to share common setup or constraints between actions.
  def policy_term_on(name)
    category = PolicyManager::Config.rules.find { |o| o.name == name }
    category.terms.last
  end
end

app/controllers/policy_manager/dashboard_controller.rb
require_dependency "terms/application_controller"

module PolicyManager
  class DashboardController < ApplicationController
  end
end

app/controllers/policy_manager/exporter_controller.rb
module PolicyManager
  class ExporterController < ActionController::Base
    include ExporterHelper
  end
end

app/controllers/policy_manager/portability_requests_controller.rb
require_dependency 'policy_manager/application_controller'
module PolicyManager
  class PortabilityRequestsController < ApplicationController
    before_action :set_portability_request, only: :destroy
    before_action :allow_admins

    # GET /portability_requests
    def index
      @portability_requests = PortabilityRequest.order(created_at: :desc)
                                                .paginate(
                                                  page: params[:page],
                                                  per_page: 20
                                                )
    end

    def confirm
      @portability_request = PortabilityRequest.find(params[:id])
      return unless @portability_request.confirm!

      redirect_to portability_requests_path
    end

    # DELETE /portability_requests/1
    def destroy
      @portability_request = PortabilityRequest.find(params[:id]).destroy
      redirect_to portability_requests_url, notice: I18n.t('terms_app.portability_requests.index.destroyed')
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_portability_request
      @portability_request = PortabilityRequest.find(params[:id])
    end
  end
end

app/controllers/policy_manager/terms_controller.rb
require_dependency 'policy_manager/application_controller'

module PolicyManager
  class TermsController < ApplicationController
    before_action :set_term, only: %i[show edit update destroy]
    before_action :allow_admins

    # GET /terms/1
    def show; end

    # GET /terms/new
    def new
      @term = Term.new
    end

    # GET /terms/1/edit
    def edit; end

    # POST /terms
    def create
      @term = Term.new(term_params)

      if @term.save
        redirect_to category_term_path(@term.rule.name, @term), notice: I18n.t('terms_app.terms.new.created')
      else
        render :new
      end
    end

    # PATCH/PUT /terms/1
    def update
      if @term.update(term_params)
        redirect_to category_term_path(@term.rule.name, @term), notice: I18n.t('terms_app.terms.new.updated')
      else
        render :edit
      end
    end

    # DELETE /terms/1
    def destroy
      @term.destroy
      redirect_to category_terms_path(@term.rule.name), notice: I18n.t('terms_app.terms.new.destroyed')
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_term
      @term = Term.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def term_params
      params.require(:term).permit(:description, :rule, :state)
    end
  end
end

app/controllers/policy_manager/user_portability_requests_controller.rb
require_dependency 'policy_manager/application_controller'

module PolicyManager
  class UserPortabilityRequestsController < ApplicationController
    def index
      @user_portability_requests = current_user.portability_requests
                                               .order(created_at: :desc)
                                               .paginate(
                                                 page: params[:page],
                                                 per_page: 20
                                               )
    end

    def create
      respond_to do |format|
        if current_user.can_request_portability?
          if current_user.portability_requests.create
            format.html do
              redirect_to user_portability_requests_path,
                          notice: I18n.t('terms_app.user_portability_requests.index.created')
            end
            format.json do
              render json: { notice: I18n.t('terms_app.user_portability_requests.index.created') }
            end
          end
        else
          format.html do
            redirect_to user_portability_requests_path,
                        notice: I18n.t('terms_app.user_portability_requests.index.has_pending')
          end
          format.json do
            render json: { notice: I18n.t('terms_app.user_portability_requests.index.has_pending') }, status: 422
          end
        end
      end
    end

    # def destroy
    #  PortabilityRequest.find(params[:id]).destroy
    #  redirect_to user_portability_requests_url, notice: I18n.t("terms_app.portability_requests.index.destroyed")
    # end
  end
end

app/controllers/policy_manager/user_terms_controller.rb
require_dependency 'policy_manager/application_controller'
require 'policy_manager/concerns/user_terms'

module PolicyManager
  class UserTermsController < ApplicationController
    include PolicyManager::Concerns::UserTerms

    skip_before_action :user_authenticated?, only: %i[show accept reject blocking_terms]
    before_action :set_user_term, only: %i[accept reject show edit update destroy]

    # GET /user_terms/1
    def show
      @user_term = if current_user.present?
                     current_user.handle_policy_for(@term)
                   else
                     UserTerm.new(term: @term, user: nil,
                                  state: cookies["policy_rule_#{@term.rule.name}"])
                   end
    end

    # GET /pending
    def pending
      @pending_policies = current_user.pending_policies
      respond_to do |format|
        format.html {}
        format.json { render json: @pending_policies }
      end
    end

    # GET /blocking_terms
    def blocking_terms
      respond_to do |format|
        format.html {}
        format.json do
          render json: PolicyManager::Config.rules
                                            .select { |p| p.blocking }
                                            .map(&:name)
        end
      end
    end

    def accept_multiples
      rules = current_user.pending_policies.map { |o| "policy_rule_#{o.name}" }
      resource_params = params.require(:user).permit(rules)
      current_user.update(resource_params)
      @pending_policies = current_user.pending_policies

      respond_to do |format|
        format.html {}
        format.json { render json: @pending_policies }
      end
    end

    def accept
      @user_term = accept_term(@term)

      respond_to do |format|
        format.html do
          if @user_term.errors.any?
            redirect_to root_url, notice: "hey there are some errors! #{@user_term.errors.full_messages.join}"
          else
            redirect_to root_url
          end
        end
        format.js
        format.json do
          render json: {
            status: @user_term ? @user_term.state : cookies["policy_rule_#{@term.rule.name}"]
          }
        end
      end
    end

    def reject
      @user_term = reject_term(@term)

      respond_to do |format|
        format.html do
          if @user_term.errors.any?
            redirect_to root_url, notice: "hey there are some errors! #{@user_term.errors.full_messages.join}"
          else
            redirect_to root_url
          end
        end
        format.js
        format.json do
          if @user_term.present? && @user_term.errors.any?
            render json: { url: root_url,
                           notice: "hey there are some errors! #{@user_term.errors.full_messages.join}" }
          else
            render json: {
              state: @user_term ? @user_term.state : cookies["policy_rule_#{@term.rule.name}"]
            }
          end
        end
      end
    end

    private

    def set_user_term
      @term = policy_term_on(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_term_params
      params.fetch(:user_term, {})
    end
  end
end

app/helpers/policy_manager/application_helper.rb
module PolicyManager
  module ApplicationHelper
    def bootstrap_class_for(flash_type)
      { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning',
        notice: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
    end

    def flash_messages(_opts = {})
      flash.each do |msg_type, message|
        flash.delete(msg_type)
        concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}") do
          concat content_tag(:button, "<i class='fa fa-times-circle'></i>".html_safe, class: 'close',
                                                                                      data: { dismiss: 'alert' })
          concat message
        end)
      end

      session.delete(:flash)
      nil
    end

    def state_color(state)
      case state
      when 'pending', 'draft'
        'tag-yellow'
      when 'progress'
        'tag-azure'
      when 'completed', 'published'
        'tag-green'
      end
    end

    def gravatar_url(user, size)
      gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
      "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    end

    def chart(data)
      column_chart(data.call)
    rescue Groupdate::Error
      content_tag(:p,
                  'chart not displayed, Be sure to install time zone support - https://github.com/ankane/groupdate#for-mysql', class: 'alert alert-danger')
    end
  end
end

app/helpers/policy_manager/categories_helper.rb
module PolicyManager
  module CategoriesHelper
  end
end

app/helpers/policy_manager/dashboard_helper.rb
module PolicyManager
  module DashboardHelper
  end
end

app/helpers/policy_manager/exporter_helper.rb
module PolicyManager
  module ExporterHelper
    def image_tag(remote_image, opts = {})
      basename = File.basename(remote_image)
      id = opts[:id] || SecureRandom.hex(10)
      composed_name = [id, basename].compact.join('-')
      path = "#{File.dirname(@base_path)}/#{composed_name}"
      save_image(remote_image, path)
      tag(:img, { src: "./#{id}-#{File.basename(URI(remote_image).path)}" }.merge(opts))
    rescue StandardError => e
      Config.error_notifier_method(e)
      content_tag(:p, 'broken image')
    end

    private

    def save_image(remote_image, path)
      open(URI(path).path, 'wb') do |file|
        file << open(remote_image).read
      end
    end
  end
end

app/helpers/policy_manager/portability_requests_helper.rb
module PolicyManager
  module PortabilityRequestsHelper
  end
end

app/views/layouts/policy_manager/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= I18n.t("terms_app.title") %></title>

  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
  <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  <%= stylesheet_link_tag    "policy_manager/application", media: "all" %>
  <%= javascript_include_tag "policy_manager/application", debug: false %>

</head>
<body>

  <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="/">
      <%= I18n.t("terms_app.sub_title") %></a>
    <ul class="navbar-nav px-3">
      <li class="nav-item text-nowrap">
        <% if PolicyManager::Config.logout_url.present? %>
          <a class="nav-link" href="<%= PolicyManager::Config.logout_url %>"><%= I18n.t("terms_app.sign_out") %></a>
        <% end %>
      </li>
    </ul>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <nav class="col-md-2 d-none d-md-block bg-light sidebar">
        <div class="sidebar-sticky">
          <ul class="nav flex-column">
            <% if PolicyManager::Config.is_admin?(controller.current_user) %>

              <li class="nav-item">
                <a class="nav-link" href="<%= categories_path %>">
                  <i class="fas fa-balance-scale"></i>
                  <%= I18n.t("terms_app.menu.policies") %>
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="<%= portability_requests_path %>">
                  <i class="fas fa-suitcase"></i>
                  <%= I18n.t("terms_app.menu.portability_requests") %>
                </a>
              </li

            <% end %>

            <% if controller.current_user.is_a? PolicyManager::Config.user_resource %>

              <li class="separator"></li>

              <li class="nav-item">
                <a class="nav-link" href="<%= pending_user_terms_path %>">
                  <i class="fas fa-user-secret"></i>
                  <%= I18n.t("terms_app.menu.user_pending_policies") %>
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="<%= user_portability_requests_path %>">
                  <i class="fas fa-suitcase"></i>
                  <%= I18n.t("terms_app.menu.user_portability_requests") %>
                </a>
              </li>

            <% end %>

          </ul>

        </div>
      </nav>

      <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
        <p id="notice">
          <%= flash_messages %>
        </p>
        <%= yield %>
      </main>
    </div>
  </div>

</body>
</html>

app/views/layouts/policy_manager/blank.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= I18n.t("terms_app.title") %></title>

  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>


  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
  <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  <%= stylesheet_link_tag    "policy_manager/application", media: "all" %>
  <%= javascript_include_tag "policy_manager/application", debug: false %>

</head>

<body>
    <%= yield %>
</body>
</html>

app/views/layouts/policy_manager/portability.erb
<body> 
  eeeee 
  <%= yield %> 
  eeee
</body>