config/routes.rb
PolicyManager::Engine.routes.draw do
  get 'documentation', to: 'application#doc', as: :documentation

  resources :user_portability_requests, only: %i[index create destroy]

  resources :portability_requests, only: %i[index destroy] do
    member do
      get :confirm
    end
  end

  resources :categories, only: %i[show index] do
    resources :terms, except: [:index]
  end

  resources :user_terms, only: [:show] do
    collection do
      get :pending
      put :accept_multiples
      get :blocking_terms
    end

    member do
      put :accept
      put :reject
    end
  end

  root 'categories#index'
end

app/models/policy_manager/application_record.rb
module PolicyManager
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/policy_manager/concerns/active_storage_behavior.rb
module PolicyManager::Concerns::ActiveStorageBehavior
  extend ActiveSupport::Concern

  included do
    has_one_attached :attachment
  end

  def file_remote_url=(url_value)
    unless url_value.blank?
      attachment.attach(
        io: File.open(url_value),
        filename: File.basename(url_value),
        content_type: 'application/zip'
      )
    end

    # self.attachment = File.open(url_value) unless url_value.blank?

    save
    complete!
  end

  def download_link
    return '' unless attachment.attached?

    url = Rails.application.routes.url_helpers.rails_blob_path(attachment, only_path: true)
    # self.attachment.expiring_url(PolicyManager::Config.exporter.expiration_link)
    PolicyManager::Config.exporter.customize_link(url)
  end
end

app/models/policy_manager/portability_request.rb
require 'aasm'

module PolicyManager
  class PortabilityRequest < ApplicationRecord
    belongs_to :user, class_name: Config.user_resource.to_s, foreign_key: :user_id

    include PolicyManager::Concerns::ActiveStorageBehavior

    include AASM

    aasm column: :state do
      state :pending, initial: true, after_enter: :notify_progress_to_admin
      state :progress, after_enter: :handle_progress
      state :completed, after_enter: :notify_completeness

      event :confirm do
        transitions from: :pending, to: :progress
      end

      event :complete do
        transitions from: :progress, to: :completed
      end
    end

    def user_email
      user.email
    end

    def handle_progress
      notify_progress
      perform_job
    end

    def perform_job
      ExporterJob.set(queue: :default).perform_later(user.id)
    end

    def notify_progress
      PortabilityMailer.progress_notification(id).deliver_now
    end

    def notify_progress_to_admin
      PortabilityMailer.admin_notification(user.id).deliver_now
    end

    def notify_completeness
      PortabilityMailer.completed_notification(id).deliver_now
    end
  end
end

app/models/policy_manager/term.rb
require 'redcarpet'
require 'aasm'

module PolicyManager
  class Term < ApplicationRecord
    include AASM

    validates_presence_of :rule
    validates_presence_of :description
    validates_presence_of :state

    aasm column: :state do
      state :draft, initial: true # db column's default
      state :published

      event :publish do
        transitions from: :draft, to: :published
      end

      event :unpublish do
        transitions from: :published, to: :draft
      end
    end

    def self.renderer
      @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
    end

    def to_html
      self.class.renderer.render(description)
    end

    def rule
      PolicyManager::Config.rules.find { |o| o.name == self[:rule] }
    end
  end
end

app/models/policy_manager/user_term.rb
require 'aasm'

module PolicyManager
  class UserTerm < ApplicationRecord
    include AASM

    belongs_to :user, class_name: Config.user_resource.to_s, foreign_key: :user_id
    belongs_to :term

    validates_uniqueness_of :term_id, scope: :user_id

    aasm column: :state do
      state :passive, initial: true
      state :rejected
      state :accepted

      event :accept do
        transitions from: %i[passive rejected], to: :accepted
      end

      event :reject do
        transitions from: %i[passive accepted], to: :rejected
      end
    end
  end
end

app/controllers/policy_manager/application_controller.rb
module PolicyManager
  class ApplicationController < ActionController::Base
    include Doorman::Controller if defined? Doorman

    before_action :user_authenticated?
    before_action :set_language

    def allow_admins
      redirect_to pending_user_terms_path unless Config.is_admin?(current_user)
    end

    def doc
      require 'redcarpet'
      @markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true,
                                                                   fenced_code_blocks: true)
      lines = File.open(PolicyManager::Engine.root.join('README.md')).readlines
      @html = @markdown.render(lines.join(''))
      render 'policy_manager/doc'
      # render inline: html, layout: "policy_manager/application"
    end

    def user_authenticated?
      return if current_user

      render file: 'policy_manager/401.erb',
             layout: 'policy_manager/blank',
             status: :unauthorized
    end

    def set_language
      I18n.locale = Config.user_language(current_user)
    end

    def current_user
      @_current_user ||= super || (Config.has_different_admin_user_resource? && admin_user)
    end

    def admin_user
      send("current_#{Config.admin_user_resource.name.underscore}")
    end

    protect_from_forgery with: :exception
  end
end

app/controllers/policy_manager/categories_controller.rb
require_dependency 'policy_manager/application_controller'

module PolicyManager
  class CategoriesController < ApplicationController
    before_action :allow_admins

    # GET /categories
    def index
      @categories = PolicyManager::Config.rules
    end

    # GET /categories/1
    def show
      @category = PolicyManager::Config.rules.find { |o| o.name == params[:id] }
      @terms = @category.terms.paginate(page: params[:page],
                                        per_page: 20)
    end
  end
end

app/controllers/policy_manager/concerns/user_terms.rb
module PolicyManager::Concerns::UserTerms
  extend ActiveSupport::Concern

  def accept_term(term)
    if current_user
      user_term = current_user.handle_policy_for(term)
      return if user_term.accepted?

      term.rule.on_accept.call(self) if user_term.accept! && term.rule.on_accept.is_a?(Proc)
    end

    cookies["policy_rule_#{term.rule.name}"] = {
      value: 'accepted',
      expires: 1.year.from_now
    }

    user_term
  end

  def reject_term(term)
    if current_user
      user_term = current_user.handle_policy_for(term)
      return if user_term.rejected?

      term.rule.on_reject.call(self) if user_term.reject! && term.rule.on_reject.is_a?(Proc)
    end

    cookies.delete("policy_rule_#{term.rule.name}")

    user_term
  end

  # Use callbacks to share common setup or constraints between actions.
  def policy_term_on(name)
    category = PolicyManager::Config.rules.find { |o| o.name == name }
    category.terms.last
  end
end

app/controllers/policy_manager/dashboard_controller.rb
require_dependency "terms/application_controller"

module PolicyManager
  class DashboardController < ApplicationController
  end
end

app/controllers/policy_manager/exporter_controller.rb
module PolicyManager
  class ExporterController < ActionController::Base
    include ExporterHelper
  end
end

app/controllers/policy_manager/portability_requests_controller.rb
require_dependency 'policy_manager/application_controller'
module PolicyManager
  class PortabilityRequestsController < ApplicationController
    before_action :set_portability_request, only: :destroy
    before_action :allow_admins

    # GET /portability_requests
    def index
      @portability_requests = PortabilityRequest.order(created_at: :desc)
                                                .paginate(
                                                  page: params[:page],
                                                  per_page: 20
                                                )
    end

    def confirm
      @portability_request = PortabilityRequest.find(params[:id])
      return unless @portability_request.confirm!

      redirect_to portability_requests_path
    end

    # DELETE /portability_requests/1
    def destroy
      @portability_request = PortabilityRequest.find(params[:id]).destroy
      redirect_to portability_requests_url, notice: I18n.t('terms_app.portability_requests.index.destroyed')
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_portability_request
      @portability_request = PortabilityRequest.find(params[:id])
    end
  end
end

app/controllers/policy_manager/terms_controller.rb
require_dependency 'policy_manager/application_controller'

module PolicyManager
  class TermsController < ApplicationController
    before_action :set_term, only: %i[show edit update destroy]
    before_action :allow_admins

    # GET /terms/1
    def show; end

    # GET /terms/new
    def new
      @term = Term.new
    end

    # GET /terms/1/edit
    def edit; end

    # POST /terms
    def create
      @term = Term.new(term_params)

      if @term.save
        redirect_to category_term_path(@term.rule.name, @term), notice: I18n.t('terms_app.terms.new.created')
      else
        render :new
      end
    end

    # PATCH/PUT /terms/1
    def update
      if @term.update(term_params)
        redirect_to category_term_path(@term.rule.name, @term), notice: I18n.t('terms_app.terms.new.updated')
      else
        render :edit
      end
    end

    # DELETE /terms/1
    def destroy
      @term.destroy
      redirect_to category_terms_path(@term.rule.name), notice: I18n.t('terms_app.terms.new.destroyed')
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_term
      @term = Term.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def term_params
      params.require(:term).permit(:description, :rule, :state)
    end
  end
end

app/controllers/policy_manager/user_portability_requests_controller.rb
require_dependency 'policy_manager/application_controller'

module PolicyManager
  class UserPortabilityRequestsController < ApplicationController
    def index
      @user_portability_requests = current_user.portability_requests
                                               .order(created_at: :desc)
                                               .paginate(
                                                 page: params[:page],
                                                 per_page: 20
                                               )
    end

    def create
      respond_to do |format|
        if current_user.can_request_portability?
          if current_user.portability_requests.create
            format.html do
              redirect_to user_portability_requests_path,
                          notice: I18n.t('terms_app.user_portability_requests.index.created')
            end
            format.json do
              render json: { notice: I18n.t('terms_app.user_portability_requests.index.created') }
            end
          end
        else
          format.html do
            redirect_to user_portability_requests_path,
                        notice: I18n.t('terms_app.user_portability_requests.index.has_pending')
          end
          format.json do
            render json: { notice: I18n.t('terms_app.user_portability_requests.index.has_pending') }, status: 422
          end
        end
      end
    end

    # def destroy
    #  PortabilityRequest.find(params[:id]).destroy
    #  redirect_to user_portability_requests_url, notice: I18n.t("terms_app.portability_requests.index.destroyed")
    # end
  end
end

app/controllers/policy_manager/user_terms_controller.rb
require_dependency 'policy_manager/application_controller'
require 'policy_manager/concerns/user_terms'

module PolicyManager
  class UserTermsController < ApplicationController
    include PolicyManager::Concerns::UserTerms

    skip_before_action :user_authenticated?, only: %i[show accept reject blocking_terms]
    before_action :set_user_term, only: %i[accept reject show edit update destroy]

    # GET /user_terms/1
    def show
      @user_term = if current_user.present?
                     current_user.handle_policy_for(@term)
                   else
                     UserTerm.new(term: @term, user: nil,
                                  state: cookies["policy_rule_#{@term.rule.name}"])
                   end
    end

    # GET /pending
    def pending
      @pending_policies = current_user.pending_policies
      respond_to do |format|
        format.html {}
        format.json { render json: @pending_policies }
      end
    end

    # GET /blocking_terms
    def blocking_terms
      respond_to do |format|
        format.html {}
        format.json do
          render json: PolicyManager::Config.rules
                                            .select { |p| p.blocking }
                                            .map(&:name)
        end
      end
    end

    def accept_multiples
      rules = current_user.pending_policies.map { |o| "policy_rule_#{o.name}" }
      resource_params = params.require(:user).permit(rules)
      current_user.update(resource_params)
      @pending_policies = current_user.pending_policies

      respond_to do |format|
        format.html {}
        format.json { render json: @pending_policies }
      end
    end

    def accept
      @user_term = accept_term(@term)

      respond_to do |format|
        format.html do
          if @user_term.errors.any?
            redirect_to root_url, notice: "hey there are some errors! #{@user_term.errors.full_messages.join}"
          else
            redirect_to root_url
          end
        end
        format.js
        format.json do
          render json: {
            status: @user_term ? @user_term.state : cookies["policy_rule_#{@term.rule.name}"]
          }
        end
      end
    end

    def reject
      @user_term = reject_term(@term)

      respond_to do |format|
        format.html do
          if @user_term.errors.any?
            redirect_to root_url, notice: "hey there are some errors! #{@user_term.errors.full_messages.join}"
          else
            redirect_to root_url
          end
        end
        format.js
        format.json do
          if @user_term.present? && @user_term.errors.any?
            render json: { url: root_url,
                           notice: "hey there are some errors! #{@user_term.errors.full_messages.join}" }
          else
            render json: {
              state: @user_term ? @user_term.state : cookies["policy_rule_#{@term.rule.name}"]
            }
          end
        end
      end
    end

    private

    def set_user_term
      @term = policy_term_on(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def user_term_params
      params.fetch(:user_term, {})
    end
  end
end

app/helpers/policy_manager/application_helper.rb
module PolicyManager
  module ApplicationHelper
    def bootstrap_class_for(flash_type)
      { success: 'alert-success', error: 'alert-danger', alert: 'alert-warning',
        notice: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
    end

    def flash_messages(_opts = {})
      flash.each do |msg_type, message|
        flash.delete(msg_type)
        concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}") do
          concat content_tag(:button, "<i class='fa fa-times-circle'></i>".html_safe, class: 'close',
                                                                                      data: { dismiss: 'alert' })
          concat message
        end)
      end

      session.delete(:flash)
      nil
    end

    def state_color(state)
      case state
      when 'pending', 'draft'
        'tag-yellow'
      when 'progress'
        'tag-azure'
      when 'completed', 'published'
        'tag-green'
      end
    end

    def gravatar_url(user, size)
      gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
      "http://gravatar.com/avatar/#{gravatar_id}.png?s=#{size}"
    end

    def chart(data)
      column_chart(data.call)
    rescue Groupdate::Error
      content_tag(:p,
                  'chart not displayed, Be sure to install time zone support - https://github.com/ankane/groupdate#for-mysql', class: 'alert alert-danger')
    end
  end
end

app/helpers/policy_manager/categories_helper.rb
module PolicyManager
  module CategoriesHelper
  end
end

app/helpers/policy_manager/dashboard_helper.rb
module PolicyManager
  module DashboardHelper
  end
end

app/helpers/policy_manager/exporter_helper.rb
module PolicyManager
  module ExporterHelper
    def image_tag(remote_image, opts = {})
      basename = File.basename(remote_image)
      id = opts[:id] || SecureRandom.hex(10)
      composed_name = [id, basename].compact.join('-')
      path = "#{File.dirname(@base_path)}/#{composed_name}"
      save_image(remote_image, path)
      tag(:img, { src: "./#{id}-#{File.basename(URI(remote_image).path)}" }.merge(opts))
    rescue StandardError => e
      Config.error_notifier_method(e)
      content_tag(:p, 'broken image')
    end

    private

    def save_image(remote_image, path)
      open(URI(path).path, 'wb') do |file|
        file << open(remote_image).read
      end
    end
  end
end

app/helpers/policy_manager/portability_requests_helper.rb
module PolicyManager
  module PortabilityRequestsHelper
  end
end

app/views/policy_manager/terms/_form.html.erb
<% path = @term.persisted? ? category_term_path(params[:category_id], @term) : category_terms_path(params[:category_id]) %>

<%= form_with(model: term, local: true, url: path ) do |form| %>
  <% if term.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(term.errors.count, "error") %> <%= I18n.t("terms_app.terms.new.error") %></h2>

      <ul>
      <% term.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :rule, value: params[:category_id] %>     
  
  <div class="form-group">
    <label><%= I18n.t("terms_app.terms.new.state") %></label>
    <%= form.select :state, PolicyManager::Term.aasm.states.collect{ |state| [I18n.t("terms_app.states.#{state}"), state] }%>   
  </div>

  <div class="form-group">
    <%= form.label I18n.t("terms_app.terms.new.description") %>
    <%= form.text_area :description, id: :term_description, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-success", value: I18n.t("terms_app.misc.save") %>
<% end %>

<script>
var simplemde = new SimpleMDE({ element: $("#term_description")[0] });
</script>

app/views/policy_manager/terms/_side.erb
<div class="col-md-3">
  <h3 class="page-title mb-5">
    <%= I18n.t("terms_app.terms.new.title", name: params[:category_id]) %>
  </h3>
  <div>
    <div class="list-group list-group-transparent mb-0">
      
      <a href="#" class="list-group-item list-group-item-action d-flex align-items-center">
        <span class="icon mr-3">
          <i class="fa fa-check"></i>
        </span>

        Published Policies on

        <strong>
        <%= params[:category_id] %>
        </strong> 
        <span class="ml-auto badge badge-primary">
          <%= PolicyManager::Term.where(rule: params[:category_id], state: "published").size %>
        </span>
      </a>

      <a href="#" class="list-group-item list-group-item-action d-flex align-items-center">
        <span class="icon mr-3">
          <i class="fa fa-exclamation-triangle"></i>
        </span>
        
        Draft Policies on 
        <strong><%= params[:category_id] %></strong>
        
        <span class="ml-auto badge badge-primary">
          <%= PolicyManager::Term.where(rule: params[:category_id], state: "draft").size %>
        </span>
      </a>

    </div>
    <div class="mt-6">
      <%= link_to I18n.t("terms_app.terms.index.button"), new_category_term_path(params[:category_id]), class:"btn btn-secondary btn-block" %>
    
    </div>
  </div>
</div>

app/views/policy_manager/terms/edit.html.erb
<div class="row">

  <%= render "side" %>
  <div class="col-md-9">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
          <%= I18n.t("terms_app.terms.edit.title", name: params[:category_id]) %>
        </h3>
      </div>
      <div class="card-body">
        <%= render 'form', term: @term %>
      </div>
    </div>
  </div>
</div>

app/views/policy_manager/terms/index.html.erb
<h2><%= I18n.t("terms_app.terms.index.title") %></h2>

<div class="float-right">
  <%= link_to I18n.t("terms_app.terms.index.button"), new_category_term_path(params[:category_id]), class: "btn btn-success" %>
</div>

<div class="table-responsive">
  <table class="table table-striped table-sm">
  <thead>
    <tr>
      <th><%= I18n.t("terms_app.terms.index.table.description") %></th>
      <th><%= I18n.t("terms_app.terms.index.table.category") %></th>
      <th><%= I18n.t("terms_app.terms.index.table.updated_at") %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @terms.each do |term| %>
      <tr>
        <td><%= truncate(term.description, length: 170, separator: " ", omission: '...') %></td>        
        <td><%= term.rule.name %></td>
        <td><%= term.updated_at %></td>
        <td><%= link_to I18n.t("terms_app.terms.index.table.show"), category_term_path(term.rule.name,term) %></td>
        <td><%= link_to I18n.t("terms_app.terms.index.table.edit"), edit_category_term_path(term.rule.name,term) %></td>
        <td><%= link_to I18n.t("terms_app.terms.index.table.destroy"), category_term_path(term.rule.name, term), method: :delete, data: { confirm: I18n.t("terms_app.misc.are_you_sure") } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/policy_manager/terms/new.html.erb
<div class="row">
  <%= render "side" %>

  <div class="col-md-9">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title">
          <%= I18n.t("terms_app.terms.new.title", name: params[:category_id]) %>
        </h3>
      </div>
      <div class="card-body">
        <%= render 'form', term: @term %>
      </div>
    </div>
  </div>
</div>

app/views/policy_manager/terms/show.html.erb
<h2>
  <%= I18n.t("terms_app.terms.show.title") %> <%= @term.rule.name %>
</h2>

<div class="card">

  <div class="card-header">
    <span class="badge-xl badge-pill badge-primary">
      <%= I18n.t("terms_app.states.#{@term.state}") %>
    </span>

    <span class="text-muted">
      <%= I18n.t("terms_app.terms.show.last_update") %> 
      <%= @term.updated_at %>
    </span>      
  </div>

  <div class="card-body">
    <%= raw @term.to_html %>
  </div>

  <div class="card-footer">
    <div class="float-right">
      <%= link_to I18n.t("terms_app.misc.back"), category_path(@term.rule.name), class: "btn-sm btn-primary" %>
      <%= link_to I18n.t("terms_app.misc.edit"), edit_category_term_path(@term.rule.name, @term), class: "btn-sm btn-success" %>      
    </div>

  </div>
</div>